### ISSUE TITLE
Socket :: Error >> Error: Server ping timed out

### ISSUE THREAD

**Issue by safiresh** [ryanpager/angularjs-socket-cluster#3]
Kindly upadate with latest verions. 
we are getting serer & client error

Server Error : 
1452428777133 - Origin: Worker (PID 2782)
   [Notice] Error: Socket Error: Client pong timed out
    at Emitter.SCSocket._onSCClose (/Users/safi/Projects/Server/hm-chat/node_modules/socketcluster-server/scsocket.js:174:17)
    at null.<anonymous> (/Users/safi/Projects/Server/hm-chat/node_modules/socketcluster-server/scsocket.js:145:10)
    at Timer.listOnTimeout (timers.js:92:15)

Cleint error: 
Socket :: Error >> Error: Server ping timed out
consoleLog/<()angular.js (line 12520)
Socket.prototype.$get</service.connect/</<(err=Object { type="object"})socket.js (line 2243)
[12]</Emitter.prototype.emit(event="error")socket.js (line 1840)
[11]</SCEmitter.prototype.emit(event="error")socket.js (line 1704)
[5]</</SCSocket.prototype._onSCError/<()socket.js (line 532)
	

return logFn.apply(console, args);

angular.js (line 12520)
![screen shot 2016-01-10 at 5 57 23 pm](https://cloud.githubusercontent.com/assets/2355624/12221505/bb381968-b7c3-11e5-81ac-d00832f57eac.png)

**Comment by ryanpager** [comment]
@safiresh Ill try to get to this tomorrow -- if not Tuesday. I use this in production on a couple things right now, so I want to make sure i have time to test everything thoroughly. Thanks for reporting!

**Comment by Anaphase** [comment]
I'm not sure an upgrade would help you with your situation, @safiresh. Could you post a basic example that demonstrates your issues so we can see if there's something wrong with your set up?

**Comment by ryanpager** [comment]
@safiresh This is now up to date -- let me know if you have any other issues. Thanks for reporting!
